### PR TITLE
Refactored the tests to use the github action

### PR DESCRIPTION
**Pull request by miazamrai**
Moved the test code to be called as github action so that the source for testing via the python sdk resides on a single place. It will allow the consumers to absorb any changes made to the test logic.

### CODE REVIEW

**Comment by miazamrai** [comment]
@larf311 @NRHelmi We need to do same kind of stuff for all the other SDKs, that is, moving the test code to a github action. It would be nice that we use the same folder github folder structure for all the SDKs.

**Comment by NRHelmi** [comment]
@miazamrai so we don't need to redefine `action.yml` in `raicode` right ?

**Comment by larf311** [comment]
Don't you need to pass in the engine version?

**Review by NRHelmi — APPROVED** [review]
thanks @miazamrai

**Comment by miazamrai** [comment]
> Don't you need to (optionally) pass in the engine version?

it will like this.
https://github.com/RelationalAI/raicode/blob/276b5325acb9daca2d453903f3712c838a228fd9/.github/workflows/raicloud-bench-sdktest-all.yml#L27

**Comment by larf311** [comment]
Is there a reason it's not to make the engine version (or perhaps custom headers) an explicit input? It would make the action self documenting. As it is now, callers of this action need to know the special environment variable to set.

**Comment by miazamrai** [comment]
@larf311 If you are agree with the current approach then I will merge this to main.

**Comment by larf311** [comment]
1. Why does a caller of the action need to know if internally it uses env variables or command line params or a config file?
2. That's why it would be an optional input
3. I don't really understand this argument.
4. You could make the input be custom headers instead of engine version to avoid this, which is probably more robust since it will allow additional functionality such as log levels, etc.

**Comment by miazamrai** [comment]
> * I don't really understand this argument.

I like #4

**Comment by miazamrai** [comment]
@larf311 Added the custom headers input param.

**Pull request merged**
