### PR TITLE
added read only user

### PR DESCRIPTION
**Pull request by staworko**
Added supported role of read only user

### CODE REVIEW

**Review by joshuafcole — APPROVED** [review]

**Comment by joshuafcole** [comment]
Just saw this -- I don't see any issue with it, but it doesn't seem like this role is mapped for any of the other SDKs. What's the story here?

**Comment by staworko** [comment]
While setting Pathfinder playgrounds for users that didnt have accounts in our latest environment, we wanted to grant them only the minimal set of privileges. It is something one can do through rai-cli or console but not python sdk. I suspect this is a result of simple omission and not an intentional choice.

**Comment by joshuafcole** [comment]
Gotcha, ship it! :shipit:

**Comment by staworko** [comment]
@dpsanders, FYI: the `USER_READ_ONLY` role will now be the main branch

**Pull request closed without merging**
